export const TRANSLATIONS = {
  en: {
    // Navbar & Navigation
    home: "Home",
    jobs: "Jobs",
    browse_jobs: "Browse Jobs",
    remote_jobs: "Remote Jobs",
    startup_jobs: "Startup Jobs",
    ai_jobs: "AI Jobs",
    internships: "Internships",
    walkin_jobs: "Walk-in Jobs",
    top_companies: "Top Companies",
    top_employers: "Top Employers",
    ai_services: "AI Services",
    mock_interview: "AI Mock Interview",
    resume_checker: "Global ATS Resume Checker",
    salary_calc: "Global PPP Salary Estimator",
    search_placeholder: "Search jobs here...",
    login: "Login",
    register: "Register",
    logout: "Logout",
    
    // Hero & Dashboard
    hero_title: "Find Verified Jobs Across 33 Major Industries in India & UAE",
    hero_desc: "Connect with top hiring teams across South Asia and Middle East. Explore visa-sponsored roles, remote contracts, and Purchasing Power Parity (PPP) salary benchmarks.",
    live_opportunities: "Live Opportunities",
    categories_title: "33 Job Categories",
    visa_relocation: "Visa & Relocation Roles",
    remote_roles: "Global Remote Roles",
    live_jobs: "Live Jobs",
    hiring_companies: "Hiring Companies",
    countries: "Countries",
    registered_professionals: "Registered Professionals",
    
    // Filters & Sidebar
    filter_jobs: "Filter Jobs",
    reset_all: "Reset All",
    location: "Location",
    region: "Region",
    country: "Country",
    state_province: "State / Province",
    city: "City",
    job_details: "Job Details",
    industry_sector: "Industry Sector (33 Sectors)",
    job_category: "Job Category",
    job_role: "Job Role / Specialization",
    experience_level: "Experience Level",
    salary_range: "Salary Range",
    work_mode: "Work Mode",
    employment_type: "Employment Type",
    advanced_filters: "Advanced Filters",
    apply_filters: "Apply Filters",
    
    // Buttons & Statuses
    apply_now: "Apply Now",
    applied: "Applied",
    easy_apply: "Easy Apply",
    featured: "Featured",
    urgent_hiring: "Urgent Hiring",
    verified: "Verified"
  },
  hi: {
    // Navbar & Navigation
    home: "मुख्य पृष्ठ",
    jobs: "नौकरियां",
    browse_jobs: "नौकरियां खोजें",
    remote_jobs: "रिमोट नौकरियां",
    startup_jobs: "स्टार्टअप नौकरियां",
    ai_jobs: "एआई नौकरियां",
    internships: "इंटर्नशिप",
    walkin_jobs: "सीधी भर्ती",
    top_companies: "शीर्ष कंपनियां",
    top_employers: "शीर्ष नियोक्ता",
    ai_services: "एआई सेवाएं",
    mock_interview: "एआई मॉक इंटरव्यू",
    resume_checker: "ग्लोबल एटीएस रिज्यूमे चेकर",
    salary_calc: "ग्لوबल पीपीपी वेतन कैलकुलेटर",
    search_placeholder: "यहां नौकरियां खोजें...",
    login: "लॉगिन",
    register: "पंजीकरण",
    logout: "लॉगआऊट",
    
    // Hero & Dashboard
    hero_title: "भारत और यूएई में 33 प्रमुख उद्योगों में सत्यापित नौकरियां खोजें",
    hero_desc: "दक्षिण एशिया और मध्य पूर्व के शीर्ष भर्तीकर्ताओं से जुड़ें। वीज़ा-प्रायोजित भूमिकाओं, रिमोट अनुबंधों और क्रय शक्ति समानता (पीपीपी) वेतन मानकों का पता लगाएं।",
    live_opportunities: "सक्रिय अवसर",
    categories_title: "33 नौकरी श्रेणियां",
    visa_relocation: "वीज़ा और स्थानांतरण",
    remote_roles: "रिमOT भूमिकाएं",
    live_jobs: "सक्रिय नौकरियां",
    hiring_companies: "भर्ती करने वाली कंपनियां",
    countries: "देश",
    registered_professionals: "पंजीकृत पेशेवर",
    
    // Filters & Sidebar
    filter_jobs: "फ़िल्टर करें",
    reset_all: "सभी रीसेट करें",
    location: "स्थान",
    region: "क्षेत्र",
    country: "देश",
    state_province: "राज्य / प्रांत",
    city: "शहर",
    job_details: "नौकरी का विवरण",
    industry_sector: "उद्योग क्षेत्र (33 क्षेत्र)",
    job_category: "नौकरी की श्रेणी",
    job_role: "भूमिका / विशेषज्ञता",
    experience_level: "अनुभव स्तर",
    salary_range: "वेतन सीमा",
    work_mode: "कार्य मोड",
    employment_type: "रोजगार का प्रकार",
    advanced_filters: "उन्नत फ़िल्टर",
    apply_filters: "फ़िल्टर लागू करें",
    
    // Buttons & Statuses
    apply_now: "अभी आवेदन करें",
    applied: "आवेदन किया गया",
    easy_apply: "आसान आवेदन",
    featured: "विशेष रुप से प्रदर्शित",
    urgent_hiring: "त्वरित भर्ती",
    verified: "सत्यापित"
  },
  ar: {
    // Navbar & Navigation
    home: "الرئيسية",
    jobs: "الوظائف",
    browse_jobs: "تصفح الوظائف",
    remote_jobs: "وظائف عن بعد",
    startup_jobs: "وظائف الشركات الناشئة",
    ai_jobs: "وظائف الذكاء الاصطناعي",
    internships: "التدريب العملي",
    walkin_jobs: "وظائف مقابلات فورية",
    top_companies: "أفضل الشركات",
    top_employers: "أفضل أصحاب العمل",
    ai_services: "خدمات الذكاء الاصطناعي",
    mock_interview: "مقابلة تجريبية بالذكاء الاصطناعي",
    resume_checker: "فاحص السيرة الذاتية ATS",
    salary_calc: "مقدر الرواتب العالمي PPP",
    search_placeholder: "ابحث عن وظائف هنا...",
    login: "تسجيل الدخول",
    register: "تسجيل جديد",
    logout: "تسجيل الخروج",
    
    // Hero & Dashboard
    hero_title: "ابحث عن وظائف موثقة في 33 قطاعًا رئيسيًا في الهند والإمارات",
    hero_desc: "تواصل مع أفضل فرق التوظيف في جنوب آسيا والشرق الأوسط. استكشف الوظائف التي توفر رعاية التأشيرة، وعقود العمل عن بعد، ومقاييس رواتب تعادل القوة الشرائية (PPP).",
    live_opportunities: "فرص عمل نشطة",
    categories_title: "33 تصنيفًا وظيفيًا",
    visa_relocation: "وظائف مع تأشيرة وانتقال",
    remote_roles: "وظائف عن بعد عالمية",
    live_jobs: "وظائف نشطة",
    hiring_companies: "الشركات الموظفة",
    countries: "البلدان",
    registered_professionals: "المحترفين المسجلين",
    
    // Filters & Sidebar
    filter_jobs: "تصفية الوظائف",
    reset_all: "إعادة تعيين الكل",
    location: "الموقع",
    region: "المنطقة",
    country: "البلد",
    state_province: "الولاية / المقاطعة",
    city: "المدينة",
    job_details: "تفاصيل الوظيفة",
    industry_sector: "قطاع الصناعة (33 قطاعًا)",
    job_category: "فئة الوظيفة",
    job_role: "الدور الوظيفي / التخصص",
    experience_level: "مستوى الخبرة",
    salary_range: "نطاق الراتب",
    work_mode: "نمط العمل",
    employment_type: "نوع التوظيف",
    advanced_filters: "تصفية متقدمة",
    apply_filters: "تطبيق التصفية",
    
    // Buttons & Statuses
    apply_now: "تقدم الآن",
    applied: "تم التقديم",
    easy_apply: "تقدم سهل",
    featured: "مميز",
    urgent_hiring: "توظيف عاجل",
    verified: "موثق"
  },
  es: {
    // Navbar & Navigation
    home: "Inicio",
    jobs: "Empleos",
    browse_jobs: "Buscar Empleos",
    remote_jobs: "Empleos Remotos",
    startup_jobs: "Empleos en Startups",
    ai_jobs: "Empleos de IA",
    internships: "Pasantías",
    walkin_jobs: "Entrevistas Directas",
    top_companies: "Mejores Empresas",
    top_employers: "Mejores Empleadores",
    ai_services: "Servicios de IA",
    mock_interview: "Simulación de Entrevista de IA",
    resume_checker: "Verificador de Currículum ATS",
    salary_calc: "Estimador de Salarios PPP",
    search_placeholder: "Buscar empleos aquí...",
    login: "Iniciar Sesión",
    register: "Registrarse",
    logout: "Cerrar Sesión",
    
    // Hero & Dashboard
    hero_title: "Encuentre empleos verificados en 33 industrias principales en India y EAU",
    hero_desc: "Conéctese con los mejores equipos de contratación de Asia del Sur y Medio Oriente. Explore roles patrocinados por visa, contratos remotos globales y puntos de referencia salariales de paridad de poder adquisitivo (PPP).",
    live_opportunities: "Oportunidades en Vivo",
    categories_title: "33 Categorías de Empleo",
    visa_relocation: "Roles con Visa y Reubicación",
    remote_roles: "Roles Remotos Globales",
    live_jobs: "Empleos en Vivo",
    hiring_companies: "Empresas Contratantes",
    countries: "Países",
    registered_professionals: "Profesionales Registrados",
    
    // Filters & Sidebar
    filter_jobs: "Filtrar Empleos",
    reset_all: "Restablecer Todo",
    location: "Ubicación",
    region: "Región",
    country: "País",
    state_province: "Estado / Provincia",
    city: "Ciudad",
    job_details: "Detalles del Empleo",
    industry_sector: "Sector Industrial (33 Sectores)",
    job_category: "Categoría de Empleo",
    job_role: "Rol / Especialización",
    experience_level: "Nivel de Experiencia",
    salary_range: "Rango Salarial",
    work_mode: "Modo de Trabajo",
    employment_type: "Tipo de Empleo",
    advanced_filters: "Filtros Avanzados",
    apply_filters: "Aplicar Filtros",
    
    // Buttons & Statuses
    apply_now: "Postularse Ahora",
    applied: "Postulado",
    easy_apply: "Postulación Rápida",
    featured: "Destacado",
    urgent_hiring: "Contratación Urgente",
    verified: "Verificado"
  }
};

export type LangCode = 'en' | 'hi' | 'ar' | 'es';

export function getTranslation(lang: LangCode, key: keyof typeof TRANSLATIONS['en']): string {
  const dict = TRANSLATIONS[lang] || TRANSLATIONS.en;
  return dict[key] || TRANSLATIONS.en[key] || key;
}
